version: '3'

services:
  backend-service:
    build: ./backend-service
    command: bash  -c 'npm install && npm run dev'
    image: backend-service
    volumes:
      - './backend-service:/usr/src/app'
    ports:
      - '9001:8080'